export const bidConstants = {
  BUYER_GET_ALL_BID_REQUEST: "BUYER_GET_ALL_BID_REQUEST",
  BUYER_GET_ALL_BID_SUCCESS: "BUYER_GET_ALL_BID_SUCCESS",
  BUYER_GET_ALL_BID_FAILURE: "BUYER_GET_ALL_BID_FAILURE",

  BUYER_BID_BY_ID_REQUEST: "BUYER_BID_BY_ID_REQUEST",
  BUYER_BID_BY_ID_SUCCESS: "BUYER_BID_BY_ID_SUCCESS",
  BUYER_BID_BY_ID_FAILURE: "BUYER_BID_BY_ID_FAILURE",

  BUYER_CREATE_BID_REQUEST: "BUYER_CREATE_BID_REQUEST",
  BUYER_CREATE_BID_SUCCESS: "BUYER_CREATE_BID_SUCCESS",
  BUYER_CREATE_BID_FAILURE: "BUYER_CREATE_BID_FAILURE",

  BUYER_BIDS_BY_USER_REQUEST: "BUYER_BIDS_BY_USER_REQUEST",
  BUYER_BIDS_BY_USER_SUCCESS: "BUYER_BIDS_BY_USER_SUCCESS",
  BUYER_BIDS_BY_USER_FAILURE: "BUYER_BIDS_BY_USER_FAILURE",

  BUYER_BIDS_POSTED_REQUEST: "BUYER_BIDS_POSTED_REQUEST",
  BUYER_BIDS_POSTED_SUCCESS: "BUYER_BIDS_POSTED_SUCCESS",
  BUYER_BIDS_POSTED_FAILURE: "BUYER_BIDS_POSTED_FAILURE",

  SELLER_GET_ALL_BID_REQUEST: "SELLER_GET_ALL_BID_REQUEST",
  SELLER_GET_ALL_BID_SUCCESS: "SELLER_GET_ALL_BID_SUCCESS",
  SELLER_GET_ALL_BID_FAILURE: "SELLER_GET_ALL_BID_FAILURE",

  SELLER_CREATE_BID_REQUEST: "SELLER_CREATE_BID_REQUEST",
  SELLER_CREATE_BID_SUCCESS: "SELLER_CREATE_BID_SUCCESS",
  SELLER_CREATE_BID_FAILURE: "SELLER_CREATE_BID_FAILURE",
};
