export const bidConstants = {
  BUYER_CREATE_BID_REQUEST: "BUYER_CREATE_BID_REQUEST",
  BUYER_CREATE_BID_SUCCESS: "BUYER_CREATE_BID_SUCCESS",
  BUYER_CREATE_BID_FAILURE: "BUYER_CREATE_BID_FAILURE",

  BUYER_UPDATE_BID_REQUEST: "BUYER_UPDATE_BID_REQUEST",
  BUYER_UPDATE_BID_SUCCESS: "BUYER_UPDATE_BID_SUCCESS",
  BUYER_UPDATE_BID_FAILURE: "BUYER_UPDATE_BID_FAILURE",

  BUYER_DELETE_BID_REQUEST: "BUYER_DELETE_BID_REQUEST",
  BUYER_DELETE_BID_SUCCESS: "BUYER_DELETE_BID_SUCCESS",
  BUYER_DELETE_BID_FAILURE: "BUYER_DELETE_BID_FAILURE",

  BUYER_GET_ALL_BID_REQUEST: "BUYER_GET_ALL_BID_REQUEST",
  BUYER_GET_ALL_BID_SUCCESS: "BUYER_GET_ALL_BID_SUCCESS",
  BUYER_GET_ALL_BID_FAILURE: "BUYER_GET_ALL_BID_FAILURE",

  SELLER_MAKE_BID_REQUEST: "SELLER_MAKE_BID_REQUEST",
  SELLER_MAKE_BID_SUCCESS: "SELLER_MAKE_BID_SUCCESS",
  SELLER_MAKE_BID_FAILURE: "SELLER_MAKE_BID_FAILURE",

  SELLER_UDPATE_BID_REQUEST: "SELLER_UDPATE_BID_REQUEST",
  SELLER_UDPATE_BID_SUCCESS: "SELLER_UDPATE_BID_SUCCESS",
  SELLER_UDPATE_BID_FAILURE: "SELLER_UDPATE_BID_FAILURE",

  SELLER_DELETE_BID_REQUEST: "SELLER_DELETE_BID_REQUEST",
  SELLER_DELETE_BID_SUCCESS: "SELLER_DELETE_BID_SUCCESS",
  SELLER_DELETE_BID_FAILURE: "SELLER_DELETE_BID_FAILURE"
};
